name: Apocalypse
version: '${project.version}'
main: apocalypse.apocalypse.Apocalypse
api-version: 1.19
commands:
  #Base controls
  toggleApocalypse:
    description: Toggles apocalypse on or off.
    usage: /toggleApocalypse [true / false]
    aliases: [ ta ]

  resetMods:
    description: Reset all player modifications.
    usage: /resetMods {@a / player names}
    aliases: [ resetm ]

  resetConfig:
    description: Resets the config to default
    usage: /resetConfig
    aliases: [ resetc ]

  #Difficulty settings
  setDifficultySetting:
    description: Changes difficulty's setting.
    usage: /setDifficultySetting [setting] {base / 0} {linear / 0} {scale / 0}
    aliases: [ setdiff, setdiffsettings ]

  saveApocalypseSettings:
    description: Save apocalypse settings to config.
    usage: /save

  #Horde settings
  setZombieType:
    description: Set properties for zombie type.
    usage: /setZombieType [type] [weight / 0] {lvlRequirement}
    aliases: [ settype ]

  createSquad:
    description: Create a squad.
    usage: /createSquad [squadName]
    aliases: [ cs ]

  setSquad:
    description: Add, change or remove zombies from squads.
    usage: /setSquad [squadName] [zombieType] [amount]
    aliases: [ ss ]

  removeSquad:
    description: Remove a squad.
    usage: /removeSquad [squadName]
    aliases: [ rs ]

  #Printing
  printHelp:
    description: Prints help for the apocalypse plugin.
    usage: /printHelp
    aliases: [ aphelp, printaphelp ]

  printDifficultySettings:
    description: Prints base difficulty settings.
    usage: /printDifficultySettings
    aliases: [ diffsets, dsets, diff ]

  printCurrentSettings:
    description: Prints current difficulty settings.
    usage: /printCurrentSettings
    aliases: [ cdiffsets, cdsets ]

  printActiveZombies:
    description: Prints how many active zombies there are.
    usage: /printActiveZombies
    aliases: [ paz ]

  printLevelSpawnPercentages:
    description: Prints level spawn chances.
    usage: /printLevelSpawnPercentages
    aliases: [ plsp, printchances ]

  printZombieTypes:
    description: Prints a table of zombie types.
    usage: /printZombieTypes
    aliases: [ pzt, printtypes ]

  printSquads:
    description: Prints a table of created squads.
    usage: /printSquads
    aliases: [ ps ]

  printMyVector:
    description: Prints your facing of vector
    usage: /printMyVector
    aliases: [ pmv ]

  #Utility
  spawnSquad:
    description: Spawns a squad on top of a player.
    usage: /spawnSquad [squadName] [level]

  despawnZombies:
    description: Despawns all active zombies.
    usage: /despawnZombies

  # Debugging
  placeBlockAtLedge:
    description: Places a glass block at a calculated ledge. Used for debugging purposes.
    usage: /placeBlockAtLedge

  placeBlockAt45:
    description: Places a block at 45 degrees angle down to NORTH
    usage: /placeBlockAt45